name = "allthingslinux"
main = ".open-next/worker.js"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

find_additional_modules = true
preserve_file_names = true

observability = { enabled = true }

# Explicitly define the environment variables that need to be made available 
# These variables are just placeholders - actual values are set in the dashboard
[vars]
NEXT_PUBLIC_URL = "https://allthingslinux.org"

# Secrets defined in the Cloudflare dashboard
# - DISCORD_WEBHOOK_URL
# - GITHUB_TOKEN
# - GITHUB_REPO_OWNER
# - GITHUB_REPO_NAME
# - MONDAY_API_KEY
# - MONDAY_BOARD_ID

