name = "allthingslinux"
main = ".open-next/worker.js"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

find_additional_modules = true
preserve_file_names = true

observability = { enabled = true }

