name = "allthingslinux"
compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[observability]
enabled = true

# Enable caching
# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "<BINDING_ID>" 