[build]
command = "NODE_VERSION=20 npm run build:content && NODE_VERSION=20 npm run build && NODE_VERSION=20 npx @opennextjs/cloudflare"
output_directory = "./.open-next/assets"

[build.environment]
NODE_VERSION = "20"
NODE_OPTIONS = "--max-old-space-size=4096"

[site]
bucket = "./.open-next/assets"

[env.production]
NODE_ENV = "production" 