[build]
command = "npm run cloudflare:pages"
base = "/"
output_directory = "./.open-next/assets"

[build.environment]
NODE_VERSION = "20"
NODE_OPTIONS = "--max-old-space-size=4096"

[site]
bucket = "./.open-next/assets"

[env.production]
NODE_ENV = "production" 