/**
 * This file is auto-generated from scripts/generate-code-of-conduct.mjs
 * Do not edit this file directly!
 */

/**
 * The code of conduct content as a markdown string
 */
export const CODE_OF_CONDUCT_CONTENT = `# Code of Conduct

Error loading code of conduct.`;

/**
 * The date when the code of conduct was last updated
 */
export const LAST_UPDATED = 'Not available';
